- hosts: server
  become: true
  gather_facts: no
  tasks:
    - name: Create information model file related to the metric to be monitored
      file:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        state: touch
        mode: u=rw,g=r,o=r
    - name: Include broker_ip_address parameter in the information model file
      lineinfile:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        line: "broker_ip_address: {{broker_ip_address}}"
        insertafter: EOF
    - name: Include topic_name parameter in the information model file
      lineinfile:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        line: "topic_name: {{topic_name}}"
        insertafter: EOF
    - name: Include device_id parameter in the information model file
      lineinfile:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        line: "device_id: {{device_id}}"
        insertafter: EOF
    - name: Include unit parameter in the information model file
      lineinfile:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        line: "unit: {{unit}}"
        insertafter: EOF
    - name: Include interval parameter in the information model file
      lineinfile:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        line: "interval: {{interval}}"
        insertafter: EOF
    - name: Include context parameter in the information model file
      lineinfile:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        line: "context: {{context}}"
        insertafter: EOF
    - name: Add key
      shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
      when: simple == "no"
    - name: Add source
      shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
      when: simple == "no"
    - name: Install filebeat
      apt:
        name: ['filebeat']
        update_cache: yes
      when: simple == "no"
    - name: Stop filebeat service
      service:
        name: filebeat
        state: stopped
      when: simple == "no"
    - name: Check if filebeat.yml has been already copied by checking a particular string
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        state: absent
        regexp: 'output.kafka:'
      register: output
    - name: Delete filebeat.yml default configuration file
      file:
        path: /etc/filebeat/filebeat.yml
        state: absent
      when: simple == "no" and not output.found
    - name: Copy filebeat.yml template
      copy:
        src: filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: 0644
      when: simple == "no" and not output.found
    - name: Replace Kafka IP
      replace:
        path: /etc/filebeat/filebeat.yml
        regexp: 'BROKER_IP_ADDRESS'
        replace: "{{broker_ip_address}}"
      when: simple == "no" and not output.found
    - name: Include the file to be monitored by Filebeat
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        line: '    - {{ monitored_file_path }}'
        insertafter: 'filebeat.inputs:'
    - name: Include the paths field
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        line: '  paths:'
        insertafter: 'filebeat.inputs:'
    - name: Include the Kafka topic
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        line: '    topic_id: {{ topic_name }}'
        insertafter: 'filebeat.inputs:'
    - name: Include the fields field
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        line: '  fields:'
        insertafter: 'filebeat.inputs:'
    - name: Include the input type field
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        line: '- input_type: log'
        insertafter: 'filebeat.inputs:'
    - name: Start filebeat service
      service:
        name: filebeat
        state: started
      when: simple == "no"
