- hosts: server
  become: true
  gather_facts: no
  tasks:
    - name: Create information model file related to the metric to be monitored
      file:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        state: touch
        mode: u=rw,g=r,o=r
    - name: Include broker_ip_address parameter in the information model file
      lineinfile:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        line: "broker_ip_address: {{broker_ip_address}}"
        insertafter: EOF
    - name: Include topic_name parameter in the information model file
      lineinfile:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        line: "topic_name: {{topic_name}}"
        insertafter: EOF
    - name: Include device_id parameter in the information model file
      lineinfile:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        line: "device_id: {{device_id}}"
        insertafter: EOF
    - name: Include unit parameter in the information model file
      lineinfile:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        line: "unit: {{unit}}"
        insertafter: EOF
    - name: Include interval parameter in the information model file
      lineinfile:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        line: "interval: {{interval}}"
        insertafter: EOF
    - name: Include context parameter in the information model file
      lineinfile:
        path: /usr/bin/{{metric_id}}-day2-config.yml
        line: "context: {{context}}"
        insertafter: EOF
    - name: Add key
      shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
      when: simple == "no"
    - name: Add source
      shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
      when: simple == "no"
    - name: Install filebeat
      apt:
        name: ['filebeat']
        update_cache: yes
      when: simple == "no"
    - name: Delete filebeat.yml default configuration file
      file:
        path: /etc/filebeat/filebeat.yml
        state: absent
      when: simple == "no"
    - name: Copy filebeat.yml template
      copy:
        src: filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: 0644
      when: simple == "no"
    - name: Replace Kafka IP
      replace:
        path: /etc/filebeat/filebeat.yml
        regexp: 'BROKER_IP_ADDRESS'
        replace: "{{broker_ip_address}}"
      when: simple == "no"
    - name: Replace Kafka topic
      replace:
        path: /etc/filebeat/filebeat.yml
        regexp: 'TOPIC_NAME'
        replace: "{{topic_name}}"
      when: simple == "no"
    - name: Replace file path
      replace:
        path: /etc/filebeat/filebeat.yml
        regexp: 'MONITORED_FILE_PATH'
        replace: "{{monitored_file_path}}"
      when: simple == "no"
    - name: Start filebeat service
      service: 
      service:
        name: filebeat
        state: started
      when: simple == "no"
