filebeat.inputs:

processors:
  - decode_csv_fields:
      fields:
        message: decoded_csv_arr
      separator: ","
      ignore_missing: false
      overwrite_keys: true
      trim_leading_space: false
      fail_on_error: true

  - script:
      lang: javascript
      id: convert_csv_into_json
      source: >
        function process(event) {
            var csv_arr = event.Get("decoded_csv_arr");
            var json_fields = ["metric_value", "timestamp", "unit", "device_id", "context"];
            var json_from_csv =  csv_arr.reduce(function(result, field, index) {
              result[json_fields[index]] = field;
              return result;
            }, {})
            json_from_csv["metric_value"] = parseFloat(json_from_csv["metric_value"])
            json_from_csv["timestamp"] = parseFloat(json_from_csv["timestamp"])
            var value = {
              value: json_from_csv
            };
            var record = [value];
            event.Put("records", record);
        }

  - drop_fields:
      fields: ["decoded_csv_arr"]

output.kafka:
  hosts: ["BROKER_IP_ADDRESS:9092"]
  topic: "%{[fields][topic_id]}"
