- hosts: server
  become: yes
  gather_facts: no
  tasks:
    - name: Execute script provided
      shell: "{{ script }}"
      register: script_exec
    - name: Print script execution
      debug:
        var: script_exec.stdout